version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "twiml-2fa"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-3iq92jh68odn"
s3_prefix = "twiml-2fa"
region = "us-west-2"
profile = "DanBartlett-Twilio-Dev"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
